# Generated by Django 5.0 on 2024-01-27 11:08

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(max_length=100)),
                ('address_line_2', models.CharField(blank=True, max_length=100, null=True)),
                ('country', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'db_table': 'tbl_department',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(max_length=100, unique=True)),
                ('days', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'LeaveType',
                'verbose_name_plural': 'LeaveTypes',
                'db_table': 'tbl_leave_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='MartialStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marital_status', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ReportingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rm_code', models.CharField(default='', max_length=100)),
                ('emp_code', models.CharField(default='', max_length=100)),
            ],
            options={
                'verbose_name': 'ReportingManager',
                'verbose_name_plural': 'ReportingManagers',
                'db_table': 'tbl_reporting_m',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ShiftTiming',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('grace_time', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'ShiftTiming',
                'verbose_name_plural': 'ShiftTimings',
                'db_table': 'tbl_shift_timing',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('is_password_changed', models.BooleanField(default=False)),
                ('user_type', models.CharField(choices=[(1, 'SuperAdmin'), (2, 'HeadHr'), (3, 'Employee')], default=1, max_length=10)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'tbl_user',
                'managed': True,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('emp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_reporting_manager', models.BooleanField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.address')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.designation')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.gender')),
                ('martial_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.martialstatus')),
                ('reporting_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.reportingmanager')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.shifttiming')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'tbl_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='HeadHr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anniversary', models.DateField(blank=True, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('emp_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_reporting_manager', models.BooleanField()),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile_pic/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.address')),
                ('admin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.department')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.designation')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.gender')),
                ('martial_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.martialstatus')),
                ('reporting_manager', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hrms.reportingmanager')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.shifttiming')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HeadHrLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('headhr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.headhr')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
            options={
                'verbose_name': 'HeadHrLeaveBalance',
                'verbose_name_plural': 'HeadHrLeaveBalances',
                'db_table': 'tbl_head_hr_leave_balance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EmpLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.employee')),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
            options={
                'verbose_name': 'EmpLeaveBalance',
                'verbose_name_plural': 'EmpLeaveBalances',
                'db_table': 'tbl_employee_leave_balance',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceHeadHr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.FloatField(default=0)),
                ('check_out', models.FloatField(default=0)),
                ('is_leave', models.BooleanField()),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('ip', models.CharField(default='', max_length=200)),
                ('longitude', models.FloatField(default=0)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('attend_image', models.ImageField(blank=True, null=True, upload_to='attend_img/')),
                ('early_late_checks', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('hrs_worked', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('regularisation_count', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_by', to='hrms.headhr')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
            options={
                'verbose_name': 'AttendanceHr',
                'verbose_name_plural': 'AttendanceHr',
                'db_table': 'tbl_attendance_headhr',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='AttendanceEmployee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.FloatField(default=0)),
                ('check_out', models.FloatField(default=0)),
                ('is_leave', models.BooleanField()),
                ('date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('latitude', models.FloatField(default=0)),
                ('ip', models.CharField(default='', max_length=200)),
                ('longitude', models.FloatField(default=0)),
                ('is_approved', models.BooleanField(blank=True, null=True)),
                ('is_rejected', models.BooleanField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
                ('attend_image', models.ImageField(blank=True, null=True, upload_to='attend_img/')),
                ('early_late_checks', models.CharField(blank=True, default='NA', max_length=100, null=True)),
                ('hrs_worked', models.CharField(blank=True, default='NA', max_length=200, null=True)),
                ('regularisation_count', models.IntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance_by', to='hrms.employee')),
                ('leave_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hrms.leavetype')),
            ],
            options={
                'verbose_name': 'AttendanceEmployee',
                'verbose_name_plural': 'AttendanceEmployees',
                'db_table': 'tbl_attendance_employee',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RegularizationEmp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regularization_type', models.CharField(choices=[('Late Coming', 'Late Coming'), ('Early Going', 'Early Going'), ('Mis Punching', 'Mis Punching')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('count', models.BigIntegerField(blank=True, default=0, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=10)),
                ('admin_comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regularizations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('destination', models.CharField(default='', max_length=200)),
                ('message', models.TextField(default='')),
                ('applied_on', models.DateField(default=django.utils.timezone.now)),
                ('is_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('is_rejected', models.BooleanField(blank=True, default=False, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_date', models.DateField(default=django.utils.timezone.now)),
                ('applied_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UserTour',
                'verbose_name_plural': 'UserTours',
                'db_table': 'tbl_users_tour',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TourExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill', models.FileField(upload_to='expense_bills/')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrms.tour')),
            ],
            options={
                'verbose_name': 'Tour Expense',
                'verbose_name_plural': 'Tour Expenses',
                'db_table': 'tbl_tour_expanse',
            },
        ),
    ]
