# Generated by Django 5.0 on 2024-01-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularizationemp',
            name='hrs_worked',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
